// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJi-uxGG8sKmHCbdkPJ6LuBWSzPAL_dKc',
    appId: '1:836753325176:web:4a89f68790ec5be858c18d',
    messagingSenderId: '836753325176',
    projectId: 'task-manager-bbi-assi',
    authDomain: 'task-manager-bbi-assi.firebaseapp.com',
    storageBucket: 'task-manager-bbi-assi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjTsql_2T1-htMtZDF_RwKJ1CWOhYXo60',
    appId: '1:836753325176:android:c73e20edc2e8d69158c18d',
    messagingSenderId: '836753325176',
    projectId: 'task-manager-bbi-assi',
    storageBucket: 'task-manager-bbi-assi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClupdZt5xZbM-t9v6SQr7QEOsxC4cJETI',
    appId: '1:836753325176:ios:d9f60555de1454d058c18d',
    messagingSenderId: '836753325176',
    projectId: 'task-manager-bbi-assi',
    storageBucket: 'task-manager-bbi-assi.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClupdZt5xZbM-t9v6SQr7QEOsxC4cJETI',
    appId: '1:836753325176:ios:d9f60555de1454d058c18d',
    messagingSenderId: '836753325176',
    projectId: 'task-manager-bbi-assi',
    storageBucket: 'task-manager-bbi-assi.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJi-uxGG8sKmHCbdkPJ6LuBWSzPAL_dKc',
    appId: '1:836753325176:web:282971a2b9625ac558c18d',
    messagingSenderId: '836753325176',
    projectId: 'task-manager-bbi-assi',
    authDomain: 'task-manager-bbi-assi.firebaseapp.com',
    storageBucket: 'task-manager-bbi-assi.firebasestorage.app',
  );
}
